version: "2"
services:
  watergo:
    container_name: watergo-dev
    build: .
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
    ports:
      - "80"
    volumes:
      - .:/site/app
      - ./docker:/docker
      - ./docker/nginx/sites-enabled:/etc/nginx/sites-enabled
      # - ~/.composer:/root/.composer
      - ./.zsh_history:/root/.zsh_history
    environment:
      - VIRTUAL_HOST=yoursite.docker
      - VIRTUAL_PORT=80
    #env_file:
      #- raven.env
      #- blog.env
  mysql:
    container_name: watergo-dev-mysql
    image: mysql:5.6
    environment:
    - VIRTUAL_HOST=mysql.watergo.local.tw
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=root
    - MYSQL_USER=docker
    - MYSQL_PASSWORD=docker
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
  redis:
    container_name: watergo-dev-redis
    image: redis:3.2-alpine
    ports:
      - "6379:6379"
    expose:
      - "6379"
